export const searchAPIData = {
  matrix: [
    {
      vote_average: 8.1,
      vote_count: 14435,
      id: 603,
      video: false,
      media_type: 'movie',
      title: 'The Matrix',
      popularity: 36.999,
      poster_path: '/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg',
      original_language: 'en',
      original_title: 'The Matrix',
      genre_ids: [28, 878],
      backdrop_path: '/icmmSD4vTTDKOq2vvdulafOGw93.jpg',
      adult: false,
      overview:
        'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
      release_date: '1999-03-30'
    },
    {
      vote_average: 6.9,
      vote_count: 5726,
      id: 604,
      video: false,
      media_type: 'movie',
      title: 'The Matrix Reloaded',
      popularity: 26.349,
      poster_path: '/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg',
      original_language: 'en',
      original_title: 'The Matrix Reloaded',
      genre_ids: [12, 28, 53, 878],
      backdrop_path: '/Fp3piEuHXxKnPBO5R0Wj4wjZHg.jpg',
      adult: false,
      overview:
        "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
      release_date: '2003-05-15'
    },
    {
      vote_average: 6.6,
      vote_count: 5145,
      id: 605,
      video: false,
      media_type: 'movie',
      title: 'The Matrix Revolutions',
      popularity: 22.419,
      poster_path: '/2aJvwc4zXqtVUDbEu62e14J0mhe.jpg',
      original_language: 'en',
      original_title: 'The Matrix Revolutions',
      genre_ids: [12, 28, 53, 878],
      backdrop_path: '/pdVHUsb2eEz9ALNTr6wfRJe5xVa.jpg',
      adult: false,
      overview:
        'The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.',
      release_date: '2003-11-05'
    },
    {
      original_name: 'Matrix',
      id: 11393,
      media_type: 'tv',
      name: 'Matrix',
      vote_count: 0,
      vote_average: 0,
      poster_path: null,
      first_air_date: '1993-03-01',
      popularity: 1.683,
      genre_ids: [18],
      original_language: 'en',
      backdrop_path: null,
      overview:
        'Matrix is the title of a Canadian-produced fantasy/adventure series that ran for 13 episodes during 1993 on the USA Network in the United States. The series later enjoyed a brief revival of interest due to a coincidence involving one of its stars.',
      origin_country: ['US', 'CA']
    },
    {
      vote_average: 6.8,
      vote_count: 102,
      id: 14543,
      video: false,
      media_type: 'movie',
      title: 'The Matrix Revisited',
      popularity: 7.658,
      poster_path: '/kR4xt6eVdTS1agmUiL4RHXEYkDs.jpg',
      original_language: 'en',
      original_title: 'The Matrix Revisited',
      genre_ids: [99],
      backdrop_path: '/lBdXACywnLwKUZmZkZ87djDQBeV.jpg',
      adult: false,
      overview:
        'The film goes behind the scenes of the 1999 sci-fi movie The Matrix.',
      release_date: '2001-11-20'
    },
    {
      original_name: 'Threat Matrix',
      id: 711,
      media_type: 'tv',
      name: 'Threat Matrix',
      vote_count: 1,
      vote_average: 1,
      poster_path: '/5WOYC0EP0y1WnH6hC8Fx0cy2hh0.jpg',
      first_air_date: '2003-09-18',
      popularity: 2.761,
      genre_ids: [18, 10759],
      original_language: 'en',
      backdrop_path: '/4va2RmogAu37bLewnRLEqpblrO3.jpg',
      overview:
        'Against the rising threat, the Homeland Security Agency has created a highly specialized, elite task force trained and equipped to counter anyone or anything that threatens our nation. The head of this super-secret team is Special Agent John Kilmer. He reports only to the President and has authority to call upon the technical skills, firepower and the specialist agents of the FBI, CIA and NSA.',
      origin_country: ['US']
    },
    {
      vote_average: 8.3,
      vote_count: 3,
      id: 562976,
      video: false,
      media_type: 'movie',
      title: 'The Matrix Revolutions Decoded',
      popularity: 3.509,
      poster_path: '/nPOD9BrSLmN2whUAwGbuqXruRFf.jpg',
      original_language: 'en',
      original_title: 'The Matrix Revolutions Decoded',
      genre_ids: [12, 28, 53, 878],
      backdrop_path: '/ga7QqSbkXSv88e3jl4DWkwpUlF1.jpg',
      adult: false,
      overview:
        '"The Matrix Revolutions Decoded" is a Matrix sequels edit. It presents a complete and focused narrative executed in the same run time as the original "The Matrix" while unveiling a brand new and more satisfying conclusion to The Matrix saga. Over 2 hours have been removed from the original source material without logical gaps or jump cuts.  The distant future: Humanity is in peril, enslaved by a machine intelligence of their own design. Neo is "The One", a human prophecied to bring about freedom for his people, but is this truly his destiny, or just another system of control?  Meanwhile, the machines begin an assault on the last human city that threatens to wipe out mankind forever.',
      release_date: '2016-08-30'
    },
    {
      vote_average: 5.4,
      vote_count: 4,
      id: 51767,
      video: false,
      media_type: 'movie',
      title: 'Sexual Matrix',
      popularity: 1.861,
      poster_path: '/leZ7bOP0wSvtweHHYwDze4m7oMr.jpg',
      original_language: 'en',
      original_title: 'Sexual Matrix',
      genre_ids: [878],
      backdrop_path: '/gIWzjbtd2XYPnu1zttI8fzG93cU.jpg',
      adult: false,
      overview:
        '"Sexual Matrix" is about a matrix that is sexual. A horny professor decides to ask his students all about their sexual fantasies. Of course he does. So while they\'re describing their wildest dreams, he plugs them into his matrix machine and it lets them live out their fantasies. It seems so real! Mia Zottoli shows up to assist the professor in his quest to know what turns the whole campus on',
      release_date: '2000-04-01'
    },
    {
      vote_average: 6.7,
      vote_count: 20,
      id: 33322,
      video: false,
      media_type: 'movie',
      title: 'Armitage III: Poly Matrix',
      popularity: 3.289,
      poster_path: '/7sUCRdjGe7VggDCGIHywfguYdAK.jpg',
      original_language: 'ja',
      original_title: 'アミテージ・ザ・サード POLY-MATRIX',
      genre_ids: [16, 878, 53],
      backdrop_path: '/zY8YvEUXwvsQFcQmzqyVQA5wq5j.jpg',
      adult: false,
      overview:
        "Ross Sylibus is assigned to a police unit on a Martian colony, to find that women are being murdered by a psychotic named D'anclaude. He is assigned a very unorthodox partner named Naomi Armitage, who seems to have links to the victims. To stir things up more, every victim is found to be an illegally made third-generation android.",
      release_date: '1997-04-08'
    },
    {
      vote_average: 6.4,
      vote_count: 20,
      id: 21769,
      video: false,
      media_type: 'movie',
      title: 'Armitage: Dual Matrix',
      popularity: 3.04,
      poster_path: '/oKP0UiMxSGT9J7wpPZnFwW4z2YY.jpg',
      original_language: 'ja',
      original_title: 'アミテージ・ザ・サード DUAL-MATRIX',
      genre_ids: [53, 28, 16, 878, 12],
      backdrop_path: '/95etXXpKuKsYFy1Cpa0ZXSTqBGk.jpg',
      adult: false,
      overview:
        'Naomi Armitage and Ross Sylibus have changed their names and live with their daughter Yoko as a happy and normal family on Mars — until an android riot breaks out at an anti-matter plant on Earth.',
      release_date: '2002-03-22'
    },
    {
      original_name: 'Matrix',
      id: 31636,
      media_type: 'tv',
      name: 'Matrix',
      vote_count: 0,
      vote_average: 0,
      poster_path: null,
      first_air_date: '',
      popularity: 0.6,
      genre_ids: [],
      original_language: 'en',
      backdrop_path: null,
      overview:
        'Matrix was an Italian news program and talks show television, broadcast on Canale 5, from 2005 and 2012, and rerun on Mediaset Plus: it was a rival program of RAI flagship news program Porta a Porta.',
      origin_country: ['IT']
    },
    {
      vote_average: 6.5,
      vote_count: 20,
      id: 221495,
      video: false,
      media_type: 'movie',
      title: 'The Matrix Recalibrated',
      popularity: 1.925,
      poster_path: '/sVP2PpetwT8Qg82M48tYA0ILije.jpg',
      original_language: 'en',
      original_title: 'The Matrix Recalibrated',
      genre_ids: [99, 878],
      backdrop_path: null,
      adult: false,
      overview:
        'The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly',
      release_date: '2004-04-06'
    },
    {
      vote_average: 0,
      vote_count: 0,
      id: 373223,
      video: false,
      media_type: 'movie',
      title: 'Matrix',
      popularity: 0.6,
      poster_path: '/wx2s9xYeC6uP2auuuVg99yl4RpU.jpg',
      original_language: 'en',
      original_title: 'Matrix',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: 'Abstract art film made for gallery exhibition.',
      release_date: '1973-01-01'
    },
    {
      vote_average: 0,
      vote_count: 0,
      id: 555879,
      video: false,
      media_type: 'movie',
      title: 'Matrix',
      popularity: 0.6,
      poster_path: '/AfFD10ZqEx2vkxM2yvRZkybsGB7.jpg',
      original_language: 'en',
      original_title: 'Matrix',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        'The film is composed of receding planes in a landscape: a back garden and the houses beyond. The wooden lattice fence, visible in the image, marks the border between enclosed and open, private and public space, and forms both a fulcrum for the work and a formal grid by which the shots are framed and organised.',
      release_date: '1998-12-31'
    },
    {
      vote_average: 0,
      vote_count: 0,
      id: 411948,
      video: false,
      media_type: 'movie',
      title: 'Matrix',
      popularity: 0.6,
      poster_path: '/cseRq8R9RGN66SNUgcD7RJAxBI7.jpg',
      original_language: 'en',
      original_title: 'Matrix',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        'John Whitney, Sr. (April 8, 1917 – September 22, 1995) was an American animator, composer and inventor, widely considered to be one of the fathers of computer animation.',
      release_date: '1971-05-18'
    },
    {
      original_name: 'Matrix Chiambretti',
      id: 68447,
      media_type: 'tv',
      name: 'Matrix Chiambretti',
      vote_count: 0,
      vote_average: 0,
      poster_path: '/vECc6k0Uzci03gyLIQOxJ1TQMNm.jpg',
      first_air_date: '2016-10-07',
      popularity: 0.6,
      genre_ids: [10767],
      original_language: 'it',
      backdrop_path: null,
      overview: '',
      origin_country: ['IT']
    },
    {
      vote_average: 3.7,
      vote_count: 3,
      id: 60215,
      video: false,
      media_type: 'movie',
      title: 'Darkdrive',
      popularity: 1.197,
      poster_path: '/f0IrDtE13MWFvbMQqAVJgVKfomd.jpg',
      original_language: 'en',
      original_title: 'Darkdrive',
      genre_ids: [878, 53],
      backdrop_path: '/Asz7nzSbjjqJ0f0e7s2pQgCiUxq.jpg',
      adult: false,
      overview:
        'Set in some distant future, one man must restore order when a mainframe system crashes in a virtual reality prison where computers control the inmates thoughts.',
      release_date: '1998-08-18'
    },
    {
      vote_average: 0,
      vote_count: 0,
      id: 259464,
      video: false,
      media_type: 'movie',
      title: 'V-World Matrix',
      popularity: 1.091,
      poster_path: '/9jdGgfQnMQ1B3qaYdtx2pMMcixV.jpg',
      original_language: 'en',
      original_title: 'V-World Matrix',
      genre_ids: [878, 14, 27],
      backdrop_path: null,
      adult: false,
      overview:
        'Two friends take a cyber vacation to experience a world where they can act out their virtual fantasies! They soon realize they\'ve entered a virtual free-for-all. Forbidden fantasies and desires suddenly appear in the form of the even deadlier "dark woman". All the players now end up in a cyber battle for their lives, and sanity, against a beautiful virtual hunter who has one killer fixation - winning the deadly game they started!',
      release_date: '1999-01-01'
    },
    {
      vote_average: 0,
      vote_count: 0,
      id: 305374,
      video: false,
      media_type: 'movie',
      title: 'Circadian Rhythm',
      popularity: 0.6,
      poster_path: '/A5wtJMu7UDlSe5AtIF2ZHNtB9Xv.jpg',
      original_language: 'en',
      original_title: 'Circadian Rhythm',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: '',
      release_date: '2005-11-03'
    },
    {
      original_name: 'Approval Matrix',
      id: 38368,
      media_type: 'tv',
      name: 'Approval Matrix',
      vote_count: 0,
      vote_average: 0,
      poster_path: null,
      first_air_date: '2011-02-16',
      popularity: 0.6,
      genre_ids: [],
      original_language: 'en',
      backdrop_path: null,
      overview: '',
      origin_country: ['US']
    }
  ]
};
